
import { create } from "zustand";
import { persist } from "zustand/middleware";

interface TranslationState {
  language: string;
  setLanguage: (language: string) => void;
  t: (key: string) => string;
}

const translations: Record<string, Record<string, string>> = {
  en: {
    dashboard: "Dashboard",
    content: "Content",
    campaigns: "Campaigns",
    bots: "Bots",
    scenarios: "Scenarios",
    analytics: "Analytics",
    command: "Command",
    settings: "Settings",
    collapse: "Collapse",
    details: "View details",
    generateContent: "Generate content",
    campaignAnalytics: "Campaign Analytics",
    campaignAnalyticsDesc: "Overview of your marketing campaign effectiveness",
    noInteractions: "No interactions in the last 30 days",
    activeBots: "Active Bots",
    activeBotsDesc: "Manage and monitor your active bots",
    noBotsRunning: "No bots currently running",
    manageBots: "Manage bots",
    recentScenarios: "Recent Scenarios",
    recentScenariosDesc: "Quick access to your latest scenarios",
    noScenarios: "No scenarios launched this week",
    manageScenarios: "Manage scenarios",
    campaignActivity: "Campaign Activity",
    noActivityYet: "No activity recorded yet",
    timeRange: "Time range",
    last24Hours: "Last 24 hours",
    last7Days: "Last 7 days",
    last30Days: "Last 30 days",
    last90Days: "Last 90 days",
    views: "Views",
    engagements: "Engagements",
    clicks: "Clicks",
    general: "General",
    apiKeys: "API Keys",
    botConfig: "Bot Config",
    proxies: "Proxies",
    security: "Security",
    billing: "Billing",
    settingsSaved: "Settings saved",
    settingsSuccessfullySaved: "Your changes have been saved successfully.",
    monitoring: "Monitoring",
    monitoringDesc: "Here you can track your bots' actions in real time",
    activity: "Activity",
    performance: "Performance",
    errors: "Errors",
    noErrors: "No critical errors",
    botsWorkingNormally: "All bots are working normally at this moment.",
    waitingForActivityData: "Waiting for activity data...",
    noActiveBotsOrData: "No active bots or no activity data",
    activateBot: "Activate a bot to start monitoring its actions in real time.",
    noActivityData: "Bots are active but there is no activity data yet. Wait for them to start working or check connection settings.",
    realTimeData: "Real-time data",
    realTimeDataDesc: "Only real bot activity data is displayed here. Start the bots to see their activity.",
  },
  ru: {
    dashboard: "Панель управления",
    content: "Контент",
    campaigns: "Кампании",
    bots: "Боты",
    scenarios: "Сценарии",
    analytics: "Аналитика",
    command: "Команды",
    settings: "Настройки",
    collapse: "Свернуть",
    details: "Подробнее",
    generateContent: "Сгенерировать контент",
    campaignAnalytics: "Аналитика кампаний",
    campaignAnalyticsDesc: "Обзор эффективности ваших маркетинговых кампаний",
    noInteractions: "Нет взаимодействий за последние 30 дней",
    activeBots: "Активные боты",
    activeBotsDesc: "Управление и мониторинг ваших активных ботов",
    noBotsRunning: "Сейчас нет запущенных ботов",
    manageBots: "Управление ботами",
    recentScenarios: "Последние сценарии",
    recentScenariosDesc: "Быстрый доступ к вашим последним сценариям",
    noScenarios: "Нет запущенных сценариев на этой неделе",
    manageScenarios: "Управление сценариями",
    campaignActivity: "Активность кампаний",
    noActivityYet: "Активность пока не зафиксирована",
    timeRange: "Период времени",
    last24Hours: "Последние 24 часа",
    last7Days: "Последние 7 дней",
    last30Days: "Последние 30 дней",
    last90Days: "Последние 90 дней",
    views: "Просмотры",
    engagements: "Взаимодействия",
    clicks: "Клики",
    general: "Общие",
    apiKeys: "API ключи",
    botConfig: "Настройки ботов",
    proxies: "Прокси",
    security: "Безопасность",
    billing: "Оплата",
    settingsSaved: "Настройки сохранены",
    settingsSuccessfullySaved: "Ваши изменения успешно сохранены.",
    monitoring: "Мониторинг",
    monitoringDesc: "Здесь вы можете отслеживать действия ваших ботов в реальном времени",
    activity: "Активность",
    performance: "Производительность",
    errors: "Ошибки",
    noErrors: "Нет критических ошибок",
    botsWorkingNormally: "В данный момент все боты работают нормально.",
    waitingForActivityData: "Ожидание данных активности...",
    noActiveBotsOrData: "Нет активных ботов или данных активности",
    activateBot: "Активируйте бота, чтобы начать мониторинг его действий в режиме реального времени.",
    noActivityData: "Боты активны, но пока нет данных о их действиях. Подождите, пока они начнут работу, или проверьте настройки подключения.",
    realTimeData: "Данные реального времени",
    realTimeDataDesc: "Здесь отображаются только реальные данные о работе ботов. Запустите ботов, чтобы увидеть их активность.",
  },
  de: {
    dashboard: "Dashboard",
    content: "Inhalt",
    campaigns: "Kampagnen",
    bots: "Bots",
    scenarios: "Szenarien",
    analytics: "Analytik",
    command: "Befehle",
    settings: "Einstellungen",
    collapse: "Einklappen",
    details: "Details anzeigen",
    generateContent: "Inhalt generieren",
    campaignAnalytics: "Kampagnen-Analytik",
    campaignAnalyticsDesc: "Überblick über die Effektivität Ihrer Marketing-Kampagnen",
    noInteractions: "Keine Interaktionen in den letzten 30 Tagen",
    activeBots: "Aktive Bots",
    activeBotsDesc: "Verwalten und überwachen Sie Ihre aktiven Bots",
    noBotsRunning: "Derzeit laufen keine Bots",
    manageBots: "Bots verwalten",
    recentScenarios: "Aktuelle Szenarien",
    recentScenariosDesc: "Schneller Zugriff auf Ihre neuesten Szenarien",
    noScenarios: "Keine Szenarien in dieser Woche gestartet",
    manageScenarios: "Szenarien verwalten",
    campaignActivity: "Kampagnenaktivität",
    noActivityYet: "Noch keine Aktivität aufgezeichnet",
    timeRange: "Zeitraum",
    last24Hours: "Letzte 24 Stunden",
    last7Days: "Letzte 7 Tage",
    last30Days: "Letzte 30 Tage",
    last90Days: "Letzte 90 Tage",
    views: "Aufrufe",
    engagements: "Interaktionen",
    clicks: "Klicks",
    general: "Allgemein",
    apiKeys: "API-Schlüssel",
    botConfig: "Bot-Konfiguration",
    proxies: "Proxys",
    security: "Sicherheit",
    billing: "Abrechnung",
    settingsSaved: "Einstellungen gespeichert",
    settingsSuccessfullySaved: "Ihre Änderungen wurden erfolgreich gespeichert.",
    monitoring: "Überwachung",
    monitoringDesc: "Hier können Sie die Aktionen Ihrer Bots in Echtzeit verfolgen",
    activity: "Aktivität",
    performance: "Leistung",
    errors: "Fehler",
    noErrors: "Keine kritischen Fehler",
    botsWorkingNormally: "Alle Bots funktionieren derzeit normal.",
    waitingForActivityData: "Warten auf Aktivitätsdaten...",
    noActiveBotsOrData: "Keine aktiven Bots oder keine Aktivitätsdaten",
    activateBot: "Aktivieren Sie einen Bot, um dessen Aktionen in Echtzeit zu überwachen.",
    noActivityData: "Bots sind aktiv, aber es gibt noch keine Aktivitätsdaten. Warten Sie, bis sie mit der Arbeit beginnen, oder überprüfen Sie die Verbindungseinstellungen.",
    realTimeData: "Echtzeit-Daten",
    realTimeDataDesc: "Hier werden nur reale Bot-Aktivitätsdaten angezeigt. Starten Sie die Bots, um ihre Aktivität zu sehen.",
  },
  fr: {
    dashboard: "Tableau de bord",
    content: "Contenu",
    campaigns: "Campagnes",
    bots: "Bots",
    scenarios: "Scénarios",
    analytics: "Analytique",
    command: "Commandes",
    settings: "Paramètres",
    collapse: "Réduire",
    details: "Voir les détails",
    generateContent: "Générer du contenu",
    campaignAnalytics: "Analytique de campagne",
    campaignAnalyticsDesc: "Aperçu de l'efficacité de vos campagnes marketing",
    noInteractions: "Aucune interaction au cours des 30 derniers jours",
    activeBots: "Bots actifs",
    activeBotsDesc: "Gérez et surveillez vos bots actifs",
    noBotsRunning: "Aucun bot actuellement en cours d'exécution",
    manageBots: "Gérer les bots",
    recentScenarios: "Scénarios récents",
    recentScenariosDesc: "Accès rapide à vos derniers scénarios",
    noScenarios: "Aucun scénario lancé cette semaine",
    manageScenarios: "Gérer les scénarios",
    campaignActivity: "Activité de campagne",
    noActivityYet: "Aucune activité enregistrée pour le moment",
    timeRange: "Période",
    last24Hours: "Dernières 24 heures",
    last7Days: "7 derniers jours",
    last30Days: "30 derniers jours",
    last90Days: "90 derniers jours",
    views: "Vues",
    engagements: "Engagements",
    clicks: "Clics",
    general: "Général",
    apiKeys: "Clés API",
    botConfig: "Configuration des bots",
    proxies: "Proxys",
    security: "Sécurité",
    billing: "Facturation",
    settingsSaved: "Paramètres enregistrés",
    settingsSuccessfullySaved: "Vos modifications ont été enregistrées avec succès.",
    monitoring: "Surveillance",
    monitoringDesc: "Ici, vous pouvez suivre les actions de vos bots en temps réel",
    activity: "Activité",
    performance: "Performance",
    errors: "Erreurs",
    noErrors: "Aucune erreur critique",
    botsWorkingNormally: "Tous les bots fonctionnent normalement en ce moment.",
    waitingForActivityData: "En attente de données d'activité...",
    noActiveBotsOrData: "Pas de bots actifs ou pas de données d'activité",
    activateBot: "Activez un bot pour commencer à surveiller ses actions en temps réel.",
    noActivityData: "Les bots sont actifs, mais il n'y a pas encore de données d'activité. Attendez qu'ils commencent à travailler ou vérifiez les paramètres de connexion.",
    realTimeData: "Données en temps réel",
    realTimeDataDesc: "Seules les données d'activité réelles des bots sont affichées ici. Démarrez les bots pour voir leur activité.",
  },
  es: {
    dashboard: "Panel de control",
    content: "Contenido",
    campaigns: "Campañas",
    bots: "Bots",
    scenarios: "Escenarios",
    analytics: "Analítica",
    command: "Comandos",
    settings: "Configuración",
    collapse: "Colapsar",
    details: "Ver detalles",
    generateContent: "Generar contenido",
    campaignAnalytics: "Analítica de campañas",
    campaignAnalyticsDesc: "Resumen de la efectividad de sus campañas de marketing",
    noInteractions: "No hay interacciones en los últimos 30 días",
    activeBots: "Bots activos",
    activeBotsDesc: "Administre y monitoree sus bots activos",
    noBotsRunning: "No hay bots funcionando actualmente",
    manageBots: "Administrar bots",
    recentScenarios: "Escenarios recientes",
    recentScenariosDesc: "Acceso rápido a sus escenarios más recientes",
    noScenarios: "No hay escenarios lanzados esta semana",
    manageScenarios: "Administrar escenarios",
    campaignActivity: "Actividad de campaña",
    noActivityYet: "Aún no se ha registrado actividad",
    timeRange: "Periodo de tiempo",
    last24Hours: "Últimas 24 horas",
    last7Days: "Últimos 7 días",
    last30Days: "Últimos 30 días",
    last90Days: "Últimos 90 días",
    views: "Vistas",
    engagements: "Interacciones",
    clicks: "Clics",
    general: "General",
    apiKeys: "Claves API",
    botConfig: "Configuración de bots",
    proxies: "Proxys",
    security: "Seguridad",
    billing: "Facturación",
    settingsSaved: "Configuración guardada",
    settingsSuccessfullySaved: "Sus cambios se han guardado correctamente.",
    monitoring: "Monitoreo",
    monitoringDesc: "Aquí puede seguir las acciones de sus bots en tiempo real",
    activity: "Actividad",
    performance: "Rendimiento",
    errors: "Errores",
    noErrors: "Sin errores críticos",
    botsWorkingNormally: "Todos los bots están funcionando normalmente en este momento.",
    waitingForActivityData: "Esperando datos de actividad...",
    noActiveBotsOrData: "No hay bots activos o no hay datos de actividad",
    activateBot: "Active un bot para comenzar a monitorear sus acciones en tiempo real.",
    noActivityData: "Los bots están activos, pero aún no hay datos sobre sus acciones. Espere a que comiencen a trabajar o verifique la configuración de conexión.",
    realTimeData: "Datos en tiempo real",
    realTimeDataDesc: "Aquí solo se muestran datos reales sobre el funcionamiento de los bots. Inicie los bots para ver su actividad.",
  },
  zh: {
    dashboard: "仪表板",
    content: "内容",
    campaigns: "活动",
    bots: "机器人",
    scenarios: "场景",
    analytics: "分析",
    command: "命令",
    settings: "设置",
    collapse: "折叠",
    details: "查看详情",
    generateContent: "生成内容",
    campaignAnalytics: "活动分析",
    campaignAnalyticsDesc: "营销活动效果概览",
    noInteractions: "过去30天没有互动",
    activeBots: "活跃机器人",
    activeBotsDesc: "管理和监控您的活跃机器人",
    noBotsRunning: "当前没有运行的机器人",
    manageBots: "管理机器人",
    recentScenarios: "最近的场景",
    recentScenariosDesc: "快速访问您最新的场景",
    noScenarios: "本周没有启动任何场景",
    manageScenarios: "管理场景",
    campaignActivity: "活动动态",
    noActivityYet: "尚未记录活动",
    timeRange: "时间范围",
    last24Hours: "过去24小时",
    last7Days: "过去7天",
    last30Days: "过去30天",
    last90Days: "过去90天",
    views: "查看量",
    engagements: "互动",
    clicks: "点击量",
    general: "常规",
    apiKeys: "API密钥",
    botConfig: "机器人配置",
    proxies: "代理",
    security: "安全",
    billing: "账单",
    settingsSaved: "设置已保存",
    settingsSuccessfullySaved: "您的更改已成功保存。",
    monitoring: "监控",
    monitoringDesc: "在这里您可以实时跟踪您的机器人的行动",
    activity: "活动",
    performance: "性能",
    errors: "错误",
    noErrors: "没有严重错误",
    botsWorkingNormally: "当前所有机器人都正常工作。",
    waitingForActivityData: "等待活动数据...",
    noActiveBotsOrData: "没有活跃的机器人或活动数据",
    activateBot: "激活一个机器人以开始实时监控其行动。",
    noActivityData: "机器人处于活动状态，但还没有关于它们行动的数据。等待它们开始工作，或检查连接设置。",
    realTimeData: "实时数据",
    realTimeDataDesc: "这里只显示机器人的真实活动数据。启动机器人以查看其活动。",
  }
};

// Добавляем персистентность для сохранения выбранного языка
export const useTranslation = create<TranslationState>()(
  persist(
    (set, get) => ({
      language: "ru", // Default language
      setLanguage: (language: string) => set({ language }),
      t: (key: string) => {
        const { language } = get();
        return translations[language]?.[key] || key;
      },
    }),
    {
      name: "language-storage", // имя в localStorage
    }
  )
);
